import os 

# S3
S3_ACCESS_KEY_ID = os.getenv('S3_ACCESS_KEY_ID')
S3_SECRET_ACCESS_KEY = os.getenv('S3_SECRET_ACCESS_KEY')
S3_ROLE_ARN = os.getenv('S3_ROLE_ARN')
S3_BUCKET_NAME = os.getenv('S3_BUCKET_NAME', 'creativeai-20221111143400')

# HUGGINGFACE DATASET
HF_DATASET = os.getenv("HF_DATASET")

# BACKEND
BACKEND_URL = os.getenv("BACKEND_URL")